artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: knkarthick/samsum       # # Hugging Face dataset
  raw_dataset_dir: artifacts/data_ingestion/samsum_dataset


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail
 