artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: knkarthick/samsum       # # Hugging Face dataset
  raw_dataset_dir: artifacts/data_ingestion/samsum_dataset

 